spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DB_PASSWORD}
    password: ${DB_USERNAME}
server:
    port: 8888
logging:
  level:
    org.springframework.security: DEBUG